### sHydrology packages

library(shiny)
library(shinyjs)
library(markdown)
library(jsonlite)
library(lubridate)
library(date)
library(zoo)
library(xts)
library(broom)
library(plyr)
library(dplyr)
library(tidyr)
library(purrr)
library(formattable)
library(lmomco)
library(cvequality)
library(dygraphs)
library(ggplot2)
library(gridExtra)
library(leaflet)
library(scales)
library(segmented)
library(DT)
library(bitops)
library(segmented)
library(caTools)
library(forcats)



source("pkg/js.R", local = TRUE)
source("pkg/html.R", local = TRUE)

source("functions/globals.R", local = TRUE)
source("functions/monthly35.R", local = TRUE)
source("functions/baseflow_range.R", local = TRUE)
source("functions/hydrograph_recession_coef.R", local = TRUE)
source("functions/hydrograph_separation.R", local = TRUE)
source("functions/hydrograph_parsing.R", local = TRUE)
source("functions/hydrograph_parsing_plot.R", local = TRUE)
source("functions/hydrograph_frequency_analysis.R", local = TRUE)
source("functions/hydrograph_fdc.R", local = TRUE)
source("functions/hydrograph_monthly_bar.R", local = TRUE)
source("functions/iha.R", local = TRUE)
source("functions/piecewiseReg.R", local = TRUE)
source("functions/return-period-q.R", local = TRUE)
source("functions/integer-breaks.R", local = TRUE)